# Generated by Django 5.0.2 on 2024-02-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portatil',
            fields=[
                ('referencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('fechaLanzamiento', models.DateField()),
                ('tamaño', models.SmallIntegerField(default=0)),
                ('precio', models.BigIntegerField(default=0)),
                ('procesador', models.CharField(max_length=50)),
                ('ram', models.SmallIntegerField(default=0)),
                ('rom', models.SmallIntegerField(default=0)),
                ('sinopsis', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Portatil', to='authApp.portatil')),
            ],
        ),
    ]
