# Generated by Django 5.0.2 on 2024-02-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portatil',
            name='tamaño',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
