# Generated by Django 3.2.7 on 2024-02-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_portatil_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portatil',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
