# Generated by Django 3.2.7 on 2024-02-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20240228_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
